# Generated by Django 4.2.7 on 2025-12-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='Aadhaar or National ID', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='document_id',
            field=models.CharField(blank=True, help_text='Internal document/id reference', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN (India) or Tax ID', max_length=20),
        ),
    ]
