# Generated by Django 4.2.7 on 2025-12-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_aadhaar_number_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/address/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_document_photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/id/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_document_photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/pan/'),
        ),
    ]
